spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/KIRIN_RESERVE
    username: KIRIN_DEV
    password: ${MYSQL_PASSWORD}

line:
  bot:
    channel-token: ${LINE_BOT_CHANNEL_TOKEN}
    channel-secret: ${LINE_BOT_CHANNEL_SECRET}
